name: Publish

on:
  release:
    types: [ published ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
      
    - name: Restore NuGet packages
      run: nuget restore IslandConverter.sln
      
    - name: Build the solution
      run: msbuild IslandConverter.sln /property:Configuration=Release
      
    - name: Rename net452 to IslandConverter.${{ github.ref_name }}
      run: ren IslandConverter\bin\x86\Release\net452 IslandConverter.${{ github.ref_name }}
      
    - name: Zip to IslandConverter.${{ github.ref_name }}.zip
      uses: thedoctor0/zip-release@main
      with:
        path: IslandConverter\bin\x86\Release\IslandConverter.${{ github.ref_name }}
        filename: IslandConverter.${{ github.ref_name }}.zip
      
    - name: Upload IslandConverter.${{ github.ref_name }}.zip to latest release
      uses: ncipollo/release-action@v1
      with:
        artifacts: IslandConverter.${{ github.ref_name }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
